### ISSUE TITLE
Is it possible to do autoscaling keycloak given that it is a statefulset kind

### ISSUE THREAD

**Issue by abhishekraghav** [galexrt/kubernetes-keycloak#4]
@galexrt 
If I scale manually scale the keycloak cluster like this:
`kubectl scale --replicas=3 statefulset/keycloak` it works like charm, I could see new nodes being added to the cluster and cache rebalancing happening smoothly.

But then , If i want to autoscale it I see something like this:-
```
$ kubectl autoscale statefulset keycloak --cpu-percent=50 --min=2 --max=6
error: cannot autoscale a {apps StatefulSet} 
```

So my question is, is it even possible to autoscale the keycloak stateful. Or do we need some other mechanism to achieve this. 

Thanks.

**Comment by galexrt** [comment]
@abhishekraghav This depends on your Kubernetes version, see https://github.com/kubernetes/kubernetes/issues/44033#issuecomment-364529825.
The comment suggest that it should work (though depends on if the K8S version you are on already has that for StatefulSet).

**Comment by abhishekraghav** [comment]
@galexrt Thanks. 
This Sounds good. 
Well I am using Kubernetes version 1.10, which supports stateful set.
So that means, it should support auto scaling.

From the comment given in the above thread..

> If statefulset has a scale subresource already, then it's automatically supported in the HPA....

I didn't understand what's - "scaling a subresource" means here and how does it relate in case of keycloak.
Thanks.

**Comment by galexrt** [comment]
@abhishekraghav It is a question of the StatefulSet Kubernetes object implementing the `scale` subresource/interface, which doesn't seem to work in your case for whatever reason. Have you already tried to manually create a HorizontalPodScaler targeting the StatefulSet instead of using the `kubectl autoscale` command?

As this is not a problem of this project, but a Kubernetes question, I'm closing the issue.

**Comment by abhishekraghav** [comment]
Yes I tried that as well. But for some reason it is not able to get the metrics of usage. After creating HPA pointing my keycloak statefulSet, I did 

`$ kubectl describe hpa/keycloak-hpa`

For which I get the following Output:-

```
$ kubectl describe hpa/keycloak-hpa
Name:                                                  keycloak-hpa
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Mon, 27 Aug 2018 00:47:37 +0530
Reference:                                             StatefulSet/keycloak
Metrics:                                               ( current / target )
  resource memory on pods:                             <unknown> / 475Mi
  resource cpu on pods  (as a percentage of request):  <unknown> / 50%
Min replicas:                                          2
Max replicas:                                          3
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
Events:
  Type     Reason                        Age                   From                       Message
  ----     ------                        ----                  ----                       -------
  Warning  FailedComputeMetricsReplicas  30m (x1922 over 17h)  horizontal-pod-autoscaler  failed to get memory utilization: unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
  Warning  FailedGetResourceMetric       43s (x1982 over 17h)  horizontal-pod-autoscaler  unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)

```

**Comment by galexrt** [comment]
@abhishekraghav You need to have a metrics server running in your Kubernetes cluster for HPA to work.. https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/#metrics-server

I would recommend to read up on Kubernetes and in general on such problems on your own (Kubernetes.io docs, Kubernetes StackOverflow, etc).
